# Generated by Django 4.0.4 on 2022-05-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bird'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='text',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
