# Generated by Django 4.0.4 on 2022-05-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_text_customer_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='address_type',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='contact',
        ),
    ]
