# Generated by Django 4.0.2 on 2022-03-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
